components:
  schemas:
    Site:
      type: object
      required:
        - name
        - entrepreneurId
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string
        address:
          type: string
        entrepreneurId:
          type: integer
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true